### ISSUE TITLE
Debian deploy

### ISSUE THREAD

**Issue by apolloclark** [Azure/packer-azure#178]
What do I put in for the "os_image_label" for Debian 8? I can't find any documentation on this, have been searching Google for 3 hours.

**Comment by boumenot** [comment]
Sorry, this should be more intuitive.  Please use the following value: Debian 8 "Jessie".

I'll submit a PR to problem an example for Debian too.  Please reopen if you hit anymore issues.

**Comment by apolloclark** [comment]
Could you add a tutorial or walkthrough? I've found nothing on Google, and the examples don't explain what each key-value is, and how it maps to the azure-cli commands / values.

**Comment by boumenot** [comment]
Yes.

We have an issue open to improve the existing README.  I will also add a walkthrough too because it would be nice to have end-to-end documentation.

In case others read this thread...  You can get the image label using [Azure PowerShell](https://azure.microsoft.com/en-us/documentation/articles/powershell-install-configure/).

```powershelll
Get-AzureVMImage | ft Label,PublisherName
```

As an aside... I am working on Azure Resource Manager (ARM) support now, and doing a PR of a README and examples right now.  The azure CLI lines up much more intuitively.  Regardless, I'll be providing more documentation and examples to get people started.  Feedback is **always** appreciated though!

**Comment by apolloclark** [comment]
Awesome, looking forward to it. :) Can you get the image-label through the azure cli? I'm on Ubuntu 15.10.

**Comment by boumenot** [comment]
Unfortunately, you cannot.  :disappointed: I have delivered that feedback to the appropriate internal party to get this addressed.
