### ISSUE TITLE
Packer Username Does Not Have Sudo Rights Without Password in CentOS

### ISSUE THREAD

**Issue by boumenot** [Azure/packer-azure#196]
ARM provisions a user (packer), and uses this username for all provisioning operations.  This user does not have sudo rights without a password in the CentOS/OpenLogic images and it causes provisioning to fail.

We need to handle this so customer can be successful with these images.

**Comment by boumenot** [comment]
I believe this issue is address with PR #202.

**Comment by lbielefeld** [comment]
I'm confused about whether you consider this issue resolved.  We would like to be able to create an image with a user that authenticates using a key only, with no password, and then can automatically use sudo with no password.  This seems to be what happens when I create an image using the GUI.  I can now use sudo with packer by piping the password into the sudo command, but I still have to have a password.

**Comment by boumenot** [comment]
Yes, I think it is resolved, but please correct me as appropriate.  I updated the [examples](https://github.com/Azure/packer-azure/tree/master/config_examples/arm) based on how the various distros expect sudo to be executed.  The Packer's provisioner's execute command should look like this for CentOS (don't forget the other configuration pieces).

```json
"provisioners": [ 
 { 
  "execute_command": "echo '{{user `ssh_pass`}}' | {{ .Vars }} sudo -S -E sh '{{ .Path }}'",
 }
]
```
