### ISSUE TITLE
Empty Artifact returned by azure-arm builder

### ISSUE THREAD

**Issue by arsenvlad** [Azure/packer-azure#220]
![packerscreenshot1](https://cloud.githubusercontent.com/assets/1821568/13822139/7770e6d2-eb72-11e5-9f70-f56db1094adb.png)

Currently, the URL of the captured image is not returned as part of the artifact.

**Comment by tposlins** [comment]
I have the exact same issue.   My builder capture configuration is as in the examples:
"capture_container_name": "images",
"capture_name_prefix": "packer"
In the end the temporary vhd is deleted.

**Comment by paulmey** [comment]
Yup. Any other info you'd like in there? (so that we can design it right in one go)

**Comment by arsenvlad** [comment]
AWS returns: Amis, BuilderIdValue, EC2 Conn
Digital Ocean returns: Snapshot Name, Snapshot ID, Region Name, Client
Google returns: Image Name, Driver
OpenStack returns: ImageId, BuilderIdValue, Client
File returns: Filename
Docker returns: IdValue, BuilderIdValue, Driver

For Azure, it would be convenient to have access to the following types of fields:
•	Captured Disk Storage Account Location
•	Captured Disk Storage Account Name
•	Captured Disk Storage Account Container
•	Captured Disk Blob Name
•	Captured Disk Full URI
•	Captured Disk Full URI with SAS read access (for X days)
•	Captured VM JSON template (if any is generated during capture process) for easier recreation of the VM 

Will the capture ever have more than 1 disk?

**Comment by paulmey** [comment]
Thanks for that list. The capture currently has only one disk because the default template that we use has only one disk. I'd say there could be more than one, since I would not want to exclude using custom templates at some point in the future.
So then we'll have a list of disks and the JSON template?

**Comment by arsenvlad** [comment]
For multi-disk captures (where there is one OS Disk and multiple Data Disks) the artifact would need to include the list of disks with a type designating which one is the OS, which are the data disks, and their LUNs.

**Comment by boumenot** [comment]
Fixed with PR #236.

The artifact outputs the following data.

 * Storage Account Location
 * OS Disk URI
 * SAS URI of the OS Disk that's good for 30 days.
 * Template URI
 * SAS URI of the Template that's good for 30 days.

We removed storage account name, blob, and container because they can be determined by the URI.

We do not handle the case of multi-disk captures.  I will open a new issue to track this.
